sudo: required
services:
  - docker

before_install:
  - docker build -t nikhil434/docker-react -f Dockerfile.dev .

script:
  - docker run nikhil434/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-363276436795"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
